#!/usr/bin/env bash
# =============================================================================
# DocMind — One-Time Setup Script
# Run this ONCE on your Mac to create a permanent Cloudflare Tunnel and
# install a macOS LaunchAgent so the backend starts automatically on boot.
#
# Usage:
#   chmod +x scripts/setup-tunnel.sh
#   ./scripts/setup-tunnel.sh
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$REPO_DIR/backend"
TUNNEL_NAME="docmind-api"
LAUNCHD_LABEL="com.docmind.backend"
PLIST_PATH="$HOME/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
LOG_DIR="$REPO_DIR/logs"
CLOUDFLARED_CONFIG="$HOME/.cloudflared/config.yml"

echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║  DocMind — Permanent Backend Setup            ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""

# ── 0. Prereq checks ─────────────────────────────────────────────────────────
for cmd in cloudflared python3; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "❌ Missing: $cmd — install it first."
    echo "   cloudflared: brew install cloudflared"
    exit 1
  fi
done

mkdir -p "$LOG_DIR"

# ── 1. Log in to Cloudflare (opens browser, one-time) ────────────────────────
echo "► Step 1/4: Cloudflare Login"
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
  echo "  A browser window will open — log into your Cloudflare account."
  cloudflared tunnel login
else
  echo "  Already logged in ✓"
fi

# ── 2. Create named tunnel (gives a permanent stable UUID) ───────────────────
echo ""
echo "► Step 2/4: Creating named tunnel '$TUNNEL_NAME'"
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "  Tunnel '$TUNNEL_NAME' already exists ✓"
else
  cloudflared tunnel create "$TUNNEL_NAME"
fi

# Get the tunnel's stable trycloudflare URL (UUID-based, never changes)
TUNNEL_URL=$(cloudflared tunnel info "$TUNNEL_NAME" 2>/dev/null \
  | grep -oE '[a-f0-9-]{36}\.cfargotunnel\.com' | head -1)

if [ -z "$TUNNEL_URL" ]; then
  # Fallback: extract UUID from credentials file
  TUNNEL_UUID=$(ls "$HOME/.cloudflared"/*.json 2>/dev/null | \
    xargs -I{} python3 -c "import json,sys; d=json.load(open('{}'));print(d.get('TunnelID',''))" 2>/dev/null | tail -1)
  TUNNEL_URL="${TUNNEL_UUID}.cfargotunnel.com"
fi

STABLE_URL="https://${TUNNEL_URL}"
echo "  Stable URL: $STABLE_URL ✓"

# ── 3. Write cloudflared config ──────────────────────────────────────────────
echo ""
echo "► Step 3/4: Writing cloudflared config → $CLOUDFLARED_CONFIG"
mkdir -p "$HOME/.cloudflared"

# Find credentials file
CREDS_FILE=$(ls "$HOME/.cloudflared"/*.json 2>/dev/null | head -1 || true)

cat > "$CLOUDFLARED_CONFIG" <<EOF
tunnel: $TUNNEL_NAME
credentials-file: $CREDS_FILE

ingress:
  - service: http://127.0.0.1:8000
EOF

echo "  Config written ✓"

# ── 4. Install macOS LaunchAgent ─────────────────────────────────────────────
echo ""
echo "► Step 4/4: Installing LaunchAgent → $PLIST_PATH"

# Detect venv python path
VENV_PYTHON="$BACKEND_DIR/venv/bin/python"
VENV_UVICORN="$BACKEND_DIR/venv/bin/uvicorn"
if [ ! -f "$VENV_PYTHON" ]; then
  echo "  ⚠️  No venv found at $BACKEND_DIR/venv — creating one..."
  python3 -m venv "$BACKEND_DIR/venv"
  "$BACKEND_DIR/venv/bin/pip" install -r "$BACKEND_DIR/requirements.txt" --quiet
fi

# Write the start script
START_SCRIPT="$REPO_DIR/scripts/start-backend.sh"
cat > "$START_SCRIPT" <<STARTSCRIPT
#!/usr/bin/env bash
# Auto-generated by setup-tunnel.sh — DO NOT EDIT MANUALLY
set -euo pipefail

BACKEND_DIR="$BACKEND_DIR"
LOG_DIR="$LOG_DIR"

echo "[\$(date)] Starting DocMind backend..." >> "\$LOG_DIR/backend.log"

# Start FastAPI
"\$BACKEND_DIR/venv/bin/uvicorn" app.main:app \\
  --host 127.0.0.1 --port 8000 \\
  --log-config "\$BACKEND_DIR/log_config.json" \\
  >> "\$LOG_DIR/backend.log" 2>&1 &
UVICORN_PID=\$!
echo "[\$(date)] uvicorn PID=\$UVICORN_PID" >> "\$LOG_DIR/backend.log"

# Start worker
"\$BACKEND_DIR/venv/bin/python" -m app.worker \\
  >> "\$LOG_DIR/worker.log" 2>&1 &
WORKER_PID=\$!
echo "[\$(date)] worker PID=\$WORKER_PID" >> "\$LOG_DIR/worker.log"

# Start named Cloudflare Tunnel
/opt/homebrew/bin/cloudflared tunnel run docmind-api \\
  >> "\$LOG_DIR/tunnel.log" 2>&1 &
TUNNEL_PID=\$!
echo "[\$(date)] cloudflared PID=\$TUNNEL_PID" >> "\$LOG_DIR/tunnel.log"

# Keep LaunchAgent process alive
wait \$UVICORN_PID
STARTSCRIPT
chmod +x "$START_SCRIPT"

# Write plist
cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LAUNCHD_LABEL</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$START_SCRIPT</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>KeepAlive</key>
  <true/>

  <key>WorkingDirectory</key>
  <string>$BACKEND_DIR</string>

  <key>StandardOutPath</key>
  <string>$LOG_DIR/launchd.log</string>

  <key>StandardErrorPath</key>
  <string>$LOG_DIR/launchd-error.log</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>$HOME</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
PLIST

# Load the LaunchAgent immediately
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load -w "$PLIST_PATH"
echo "  LaunchAgent installed and started ✓"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "╔═════════════════════════════════════════════════════════════════╗"
echo "║  ✅ Setup complete!                                             ║"
echo "╠═════════════════════════════════════════════════════════════════╣"
echo "║                                                                 ║"
echo "║  Permanent backend URL:                                         ║"
echo "║  $STABLE_URL"
echo "║                                                                 ║"
echo "║  Add this to Vercel Environment Variables:                      ║"
echo "║    VITE_DOCMIND_API_URL = $STABLE_URL"
echo "║                                                                 ║"
echo "║  The backend + tunnel now auto-start on every Mac boot.        ║"
echo "║  Logs: $LOG_DIR/                                ║"
echo "╚═════════════════════════════════════════════════════════════════╝"
echo ""
